/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Alumno;
import Entidades.AlumnoData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author pc202
 */
public class VistaAlumnos extends javax.swing.JInternalFrame {

  /**
   * Creates new form VistaAlumnos
   */
  public VistaAlumnos() {
    initComponents();
    jRBEstado.setEnabled(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextField4 = new javax.swing.JTextField();
    jLDocumento = new javax.swing.JLabel();
    jLApellido = new javax.swing.JLabel();
    jLNombre = new javax.swing.JLabel();
    jLEstado = new javax.swing.JLabel();
    jLFechaNacimiento = new javax.swing.JLabel();
    jBNuevo = new javax.swing.JButton();
    jBEliminar = new javax.swing.JButton();
    jBGuardar = new javax.swing.JButton();
    jTFDocumento = new javax.swing.JTextField();
    jTFApellido = new javax.swing.JTextField();
    jTFNombre = new javax.swing.JTextField();
    jBBuscar = new javax.swing.JButton();
    jRBEstado = new javax.swing.JRadioButton();
    jCFecha = new com.toedter.calendar.JDateChooser();

    jTextField4.setText("jTextField4");

    setClosable(true);
    setTitle("Alumno");

    jLDocumento.setText("Documento:");

    jLApellido.setText("Apellido:");

    jLNombre.setText("Nombre:");

    jLEstado.setText("Estado:");

    jLFechaNacimiento.setText("Fecha de Nacimiento:");

    jBNuevo.setText("Limpiar");

    jBEliminar.setText("Eliminar");

    jBGuardar.setText("Guardar");
    jBGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBGuardarActionPerformed(evt);
      }
    });

    jBBuscar.setText("Buscar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLApellido)
          .addComponent(jLNombre)
          .addComponent(jLEstado)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jLFechaNacimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jBNuevo)
                    .addGap(18, 18, 18))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLDocumento)
                    .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jRBEstado)
                  .addComponent(jTFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                  .addComponent(jTFApellido)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jBEliminar)))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jBGuardar)
            .addGap(40, 40, 40)
            .addComponent(jBBuscar)))
        .addContainerGap(42, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLDocumento)
              .addComponent(jTFDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jBBuscar))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLApellido)
              .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLNombre)
              .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLEstado)
              .addComponent(jRBEstado))
            .addGap(22, 22, 22)
            .addComponent(jLFechaNacimiento))
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBNuevo)
          .addComponent(jBEliminar)
          .addComponent(jBGuardar))
        .addGap(20, 20, 20))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
    // TODO add your handling code here:
    Date fechaDate = jCFecha.getDate();
    LocalDate fechaNac = fechaDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    String apellido = jTFApellido.getText();
    String nombre = jTFNombre.getText();
    // TODO: HACER UN TRY/CATCH !!!
    int documento = Integer.valueOf(jTFDocumento.getText());

    Alumno alumno = new Alumno(documento, apellido, nombre, fechaNac, true);
    // aData.guardarAlumno(alumno);
    limpiarCampos();
  }//GEN-LAST:event_jBGuardarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBBuscar;
  private javax.swing.JButton jBEliminar;
  private javax.swing.JButton jBGuardar;
  private javax.swing.JButton jBNuevo;
  private com.toedter.calendar.JDateChooser jCFecha;
  private javax.swing.JLabel jLApellido;
  private javax.swing.JLabel jLDocumento;
  private javax.swing.JLabel jLEstado;
  private javax.swing.JLabel jLFechaNacimiento;
  private javax.swing.JLabel jLNombre;
  private javax.swing.JRadioButton jRBEstado;
  private javax.swing.JTextField jTFApellido;
  private javax.swing.JTextField jTFDocumento;
  private javax.swing.JTextField jTFNombre;
  private javax.swing.JTextField jTextField4;
  // End of variables declaration//GEN-END:variables

  private AlumnoData aData = new AlumnoData();
  private Alumno alumnoActual = null;

  private void limpiarCampos() {
    jCFecha.setCalendar(null);
    alumnoActual = null;
    // TODO: Limpiar todos los Text Field
  }
}
